version: "3.8"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    restart: always
    depends_on:
      - db
    networks:
      - nginx-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: P@ssword123
    ports:
      - 5432:5432
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge
